Task 1.1
sgadzhanov/android-training pull request #1
Opened 2023-05-09 17:28 UTC by sgadzhanov

2023-05-11 11:32 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    val (passwordBorder, setPasswordBorder) = remember { mutableStateOf(Color.Gray) }
Use booleans with proper naming as you've used them in the `ErrorMessage` composable, for example (`emailIsValid`). Using colors for comparison is not a good idea.

2023-05-11 11:32 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +                println("email: $email, password: $password")
I am glad that you're debugging, but do try to keep the comments out of the PRs.

2023-05-11 11:32 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    Spacer(modifier = Modifier.height(10.dp))
You can chain modifiers' paddings, I suspect this is "needed" so the field can have a padding under it, but there are better ways of doing that, like utilizing the `.padding` modifier. This goes for all other composables, too.

2023-05-11 16:12 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    val (passwordBorder, setPasswordBorder) = remember { mutableStateOf(Color.Gray) }
Thanks, you are totally right! Fixed.

2023-05-11 17:03 UTC, gbuyukliev-accedia requested changes

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    val (email, setEmail) = remember { mutableStateOf("") }
The "React way" sure is an option but writing the states as a single variable is more convenient and preferable. Also, the `by` synax makes things easier as opposed to the `=` syntax.

Example: `var email by remember { mutableStateOf("") }`

Then you won't have to set its value by neither writing `setEmail("email")` or `email.value = "email"`. It would just be a simple `email = "email"`.

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    if (emailIsValid && passwordIsValid) return
It's clearer to have the conditional outside of the view instead of having it as hidden internal logic.

Example:

```
...

if (!areCredentialsValid) {
  ErrorMessage()
}

...
```

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    Column(modifier = Modifier.padding(6.dp)) {
Missing design elements here:

- Logo image
- Background image

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +        LoginTitle()
It's very nice that you have thought of separating everything into its own composable but you should always expose the modifier.

Example for LoginTitle:

```
fun LoginTitle(modifier: Modifier = Modifier) {
    Row(
        modifier = modifier
            .fillMaxWidth()
            .padding(top = 100.dp, bottom = 6.dp)
    )
}
```

This way you can supply modifier values from outside and outer paddings should **always** come from outside. The idea of a reusable view is to ensure that it won't introduce any unexpected and unclear paddings anywhere you place it.

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +            .padding(top = 100.dp, bottom = 6.dp)
Those are the paddings I was talking about. Those should never be internal.

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/MainActivity.kt
> +                                ProductDetails(goBackHandler = {
No need to be able to back to log in. Quite the opposite.

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                Spacer(Modifier.height(10.dp))
Spacers are generally used dynamically or with weight. This could be simply a top padding of the `Row` below.

2023-05-11 17:03 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                Row {
No need for `Row`s to wrap single composables. This can be just a `Text` by itself.

2023-05-11 17:05 UTC, gbuyukliev-accedia requested changes

2023-05-11 17:05 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +            Column {
Missing design elements here:

- "In stock" overlay
- Filters button

2023-05-13 12:25 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/MainActivity.kt
> +                                ProductDetails(goBackHandler = {
It was just a dummy implementation so I could just see how it works. I removed it.

2023-05-13 12:25 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +        LoginTitle()
To be honest, I don't understand it right now. I realize that it's a common good practice, but I'm not sure if I'll be able to grasp it quickly.

2023-05-13 12:25 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    Column(modifier = Modifier.padding(6.dp)) {
Added.

2023-05-13 12:26 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +            Column {
Added "In stock" overlay. Not sure what "Filters button" is.

2023-05-15 23:04 UTC, yll090 requested changes
There are a couple more comments that need to be resolved.

2023-05-15 23:04 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +        LoginTitle()
@sgadzhanov Just make a habit of exposing a `Modifier` for your composables. The example Georgi gave should be enough to get you started, but if you have any specific issues or questions regarding modifiers, or anything in between, ask in the chat (or via PM if need be).

2023-05-18 10:44 UTC, yll090 requested changes

2023-05-18 10:44 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +            Box(
`Box` is used when you want to have items overlapping each other, just the way you've used it in the shopping cart. Unles you want to have that try to prefer `Column`/`Row` for the more generic use case. Additionally, nesting those types of containers should be kept to a minimum -- it is both overhead for rerendering, as well as for reading it later. I am unsure why you've decided to have multiple `Box`es, but I think that can be optimized (it is not wrong per se, it is a bit unnecessary). Keep that in mind when doing the other homeworks.

2023-05-18 10:44 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                            Box(
This seems unnecessary wrapper, you can apply the style to the item itself.

2023-05-18 10:44 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                            modifier = Modifier
This seems unnecessary wrapper, you can apply the style to the item itself.

2023-05-18 10:44 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    ) {
This seems unnecessary wrapper, you can apply the style to the item itself.

2023-05-20 16:18 UTC, yll090 commented
@sgadzhanov There's still some comments about unnecessary wrappers that need resolving.

2023-05-26 06:24 UTC, sgadzhanov commented
I tried to fix most of the comments. I will merge the PR so that I could continue working with the other tasks!

2023-05-26 06:24 UTC, merged

2023-05-27 15:25 UTC, gbuyukliev-accedia reviewed
A couple of comments that you can look into in your future PRs.

2023-05-27 15:25 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +    val email = remember { mutableStateOf("") }
Note: `var email by remember { mutableStateOf ("") }` is an easier syntax as you don't need to refer to `.value` when working with it. The syntax you're using is good only if you want to pass the state wrapper itself to another composable and modify the inner value from there, as with the `by` syntax you won't have pass by reference on a primitive and won't be able to do that.

2023-05-27 15:25 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/Login.kt
> +                modifier = Modifier.padding(bottom = 10.dp),
Note: For readability try to always put the `modifier` argument first. Kotlin allows us to be really flexible with the argument order.

2023-05-27 15:25 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/MainActivity.kt
> +                    Scaffold {
You don't need a `Scaffold` here.