Homework 1.2
sgadzhanov/android-training pull request #2
Opened 2023-05-29 06:20 UTC by sgadzhanov

2023-05-29 06:20 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/MainActivity.kt
> +                    NavHost(
noted: redundant Scaffold removed

2023-05-29 06:21 UTC, sgadzhanov commented
Noted: tried to put the modifiers everywhere as a first argument.

2023-05-29 06:23 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +            it.onFailure { /* todo */ }
Wasn't sure what to do with the error handling, I think we will need that when we use dynamic ids and not hardcoded one.

2023-05-29 06:25 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                        val formattedPrice: String = BigDecimal(price).setScale(2).toString()
this was the first thing I found related to formatting a number. Not sure if this is the most optimal way to do it, feels a bit weird.

2023-05-29 06:26 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +    var email by remember { mutableStateOf("") }
@gbuyukliev-accedia - you were right, it feels much better to use this syntax. Thanks :)

2023-05-29 06:28 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +                ToastMessage.showToastMessage(ctx, it.message)
Used Toast instead of snackbar, I hope you will show us how to do this snackbar, it is a bit frustrating because of the material versions, at least I couldn't find a way to do this.

2023-05-29 06:29 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +                LoginErrorMessage(modifier = Modifier.padding(start = 10.dp, top = 10.dp))
I will remove this in the next PR with a snackbar

2023-06-01 17:09 UTC, yll090 requested changes

2023-06-01 17:09 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +            result.onSuccess { response: UserResponse ->
You don't really need to observe the status here. You should handle this over in the viewModel. Same goes for the `TokenProvider` -- you can, and should, inject it in the viewModel instead. The View doesn't need to know about any logic besides view (in this case -- navigation or message to the user) related.

2023-06-01 17:09 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                        val formattedPrice: String = BigDecimal(price).setScale(2).toString()
It's fine, `BigDecimal` is the go-to for currencies and any precision-related issues.

2023-06-01 17:09 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +                ToastMessage.showToastMessage(ctx, it.message)
If you can't figure it out in a reasonable time, ask in the chat, we can help with that.

2023-06-13 18:05 UTC, gbuyukliev-accedia commented
@sgadzhanov Feel free to merge this PR and resolve any leftover comments in a next one. That's why we're leaving it in the `Approved` state.

2023-06-26 11:38 UTC, merged