homework 3.1
sgadzhanov/android-training pull request #5
Opened 2023-06-29 18:25 UTC by sgadzhanov

2023-06-29 21:13 UTC, yll090 requested changes

2023-06-29 21:13 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/Search.kt
> +//@OptIn(ExperimentalMaterial3Api::class)
Remove if unnecessary.

2023-06-29 21:13 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +                clickHandler = { userViewModel.login(UserRequest(email, password)) }
In general, the view shouldn't know that we construct a request object, so it might be a better idea to delegate that to the viewmodel.

2023-06-29 21:13 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +            delay(200)
Why is the delay necessary?

2023-06-29 21:13 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        allCategories.apply { this.clear() }
No need for `this` inside, you can just `clear()` and then `addAll` inside it.

2023-06-29 21:13 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +        userViewModel.user.let { res ->
You shouldn't really rely on the `Result` object here, you can safely just use the response object itself (`UserResponse`). Since it is nullable you can safely check by its status if you're logged in or not here, too. The point is for the view to not know any business logic stuff, just models.

2023-06-29 21:13 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +    private fun getActiveFiltersCount(
Method has `get` in its name but doesn't return anything? Either return the value and set it outside or rename the method, something like `calculateActiveFiltersCount`.

2023-06-29 21:13 UTC, yll090 commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/UserViewModel.kt
> +    val user: Result<UserResponse>? by tmpUser
Again, no need to use the `Result`, you can use the model itself.

2023-06-30 08:47 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +            delay(200)
Forget to remove it, I was just testing the spinner.

2023-06-30 10:19 UTC, gbuyukliev-accedia approved these changes
A few comments. Feel free to merge if it's blocking you.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/CategoriesFilter.kt
> +        else 0f
Can be on the same line as the `if` like a ternary operator. No need to break it on two lines here.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/CategoriesFilter.kt
> +        targetValue = if (isToggled) 180f
Extract `180f` and `0f` as constants. There should be no hardcoded values or strings in the code anywhere and for anything.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/CategoriesFilter.kt
> +            .padding(top = dimensionResource(id = R.dimen.PADDING_XXL))
Wrong naming convention. Use small case, i.e: `padding_xxl`.

Note: I prefer the `_tiny`, `_very_small`, `_small`, `_regular/normal`, `_big`, `_very_big`, etc. convention but T-Shirt sizes is also fine.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/CategoriesFilter.kt
> +                    text = stringResource(id = R.string.CATEGORY),
Same comment here - wrong syntax convention. Should be in small letters. This applies to all strings/dimens/etc. values but I'll not write any more comments about them so please go over all of them.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/CategoriesFilter.kt
> +                        val category = productsViewModel.allCategories[index]
Always extract list item layouts to separate composables.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                        val formattedPrice = DecimalFormat("0.00").format(product.price)
Extract `"0.00"` to a constant for you to have a single source of truth when you're applying this to other text fields throughout the app.

Also, even a further optimization would be to extract this whole thing as an extension getter or function - I'd choose the getter, personally to avoid `()` at the end (still extract `"0.00"` to a constant, though). With an extension function this could become as simple as `val formattedPrice = product.price.asFormattedString`, provided you call your extension getter `asFormattedString`.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/login/Login.kt
> +//                    bottom = dimensionResource(id = R.dimen.PADDING_LOGO_BOTTOM)
?

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> -        println("KUREC2")
:D

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        filteredProducts.clear()
```
filteredProducts.apply {
  clear()
  addAll(allProducts)
}
```

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        filteredProducts.clear()
Use `apply` here also.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        filteredProducts.addAll(allProducts.filter { p ->
Don't use such namings like `p`. Write `product` instead or just leave the default inferred `it` without aliasing it at all.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        if (selectedCategories.count() != 4) count++
Should be != 4 but also != 0.

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        if (rating != 1) count++
Shouldn't it be != 0?

2023-06-30 10:19 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        if (price.start != 0f || price.endInclusive != 200f) count++
Don't use hardcoded values here. As pointed in another comment, extract as constants and use those constants everywhere to have a single source of truth throughout the whole app.

2023-06-30 11:48 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                        val formattedPrice = DecimalFormat("0.00").format(product.price)
I think that I did something similar to this but couldn't get rid of the braces in the end :(

2023-06-30 12:20 UTC, sgadzhanov commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        if (rating != 1) count++
I am not sure because I think that we do not have any products with less rating than 1?
If I make it  if (rating != 0), then I will already have a filter count of 1.

I will leave it as is.

2023-06-30 12:23 UTC, merged

2023-06-30 15:12 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/ProductDetails.kt
> +                        val formattedPrice = DecimalFormat("0.00").format(product.price)
Extension function (with braces - useful if you need to supply arguments):

```
fun Double.asFormattedString(): String {
...
}
```

Extension getters (without braces):

```
val Double.asFormattedString get () {
...
}
```

2023-06-30 15:14 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mobiletraining/models/viewmodels/ProductsViewModel.kt
> +        if (rating != 1) count++
What I mean is we don't have such ratings in the dataset but there might be ones. We ought to support all scenarios. The default value for the component should be "no selection", thus a 0, I think? "1 star" is already a filter condition.